# Generated by Django 5.1.5 on 2025-02-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_created_at_transaction_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='created_at',
        ),
    ]
